dist: xenial
sudo: required
language:
  - c++
addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "ppa:beineri/opt-qt-5.11.1-xenial"
    update: true
    packages:
      - qt511-meta-full
      - libbullet-dev
matrix:
  include:
    - os: linux
      compiler: gcc
      env: build_name=gcc_cmake
      script:
        - export QT_SELECT="opt-qt511"
        - mkdir build
        - cd ./build
        - cmake -DQt5Widgets_DIR=/opt/qt511/lib/cmake/Qt5Widgets/ ..
        - cmake --build . --target install
    - os: linux
      compiler: gcc
      env: build_name=gcc_qmake
      script:
        - export QT_SELECT="opt-qt511"
        - mkdir qmake_build
        - cd ./qmake_build
        - qmake ..
        - make
        - make install
    - os: linux
      compiler: clang
      env: build_name=clang_cmake
      script:
        - export QT_SELECT="opt-qt511"
        - mkdir build
        - cd ./build
        - cmake -DQt5Widgets_DIR=/opt/qt511/lib/cmake/Qt5Widgets/ ..
        - cmake --build . --target install
    - os: linux
      compiler: clang
      env: build_name=clang_qmake
      script:
        - export QT_SELECT="opt-qt511"
        - mkdir qmake_build
        - cd ./qmake_build
        - qmake ..
        - make
        - make install