dist: xenial
sudo: required
language:
  - c++
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.1-xenial
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot
  - sudo apt-get install qtbase5-dev gcc-7 g++-7 cmake qt511-meta-full
matrix:
  include:
    - script:
        # Setup
        - export CC=/usr/bin/gcc-7
        - export CXX=/usr/bin/g++-7
        - export QT_SELECT="opt-qt511"
        # Run your build commands next
        - mkdir cmake_build
        - cd ./cmake_build
        - qmake --version
        - qtchooser -print-env
        - qtchooser -l
        - cmake -DQt5Widgets_DIR=/opt/qt511/lib/cmake/Qt5Widgets/ ..
        - cmake --build . --target install
    - script:
        # Setup
        - export CC=/usr/bin/gcc-7
        - export CXX=/usr/bin/g++-7
        - QT_SELECT=5
        # Run your build commands next
        - mkdir qmake_build
        - cd ./qmake_build
        - qmake --version
        - qtchooser -print-env
        - qtchooser -l
        - qmake --version
        - qmake ..
        - make