language: c++
matrix:
  include:
    - name: "linux cmake gcc"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: required
      env: QT_SELECT="opt-qt511"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:beineri/opt-qt-5.11.1-xenial"
          update: true
          packages:
            - qtbase5-dev
            - qt511-meta-full
            - libbullet-dev
      script:
        - mkdir build
        - cd ./build
        - cmake -DQt5Widgets_DIR=/opt/qt511/lib/cmake/Qt5Widgets/ ..
        - cmake --build . --target install

    - name: "linux qmake gcc"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: required
      env: QT_SELECT="opt-qt511"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:beineri/opt-qt-5.11.1-xenial"
          update: true
          packages:
            - qtbase5-dev
            - qt511-meta-full
            - libbullet-dev
      script:
        - mkdir build
        - cd ./build
        - qmake ..
        - make
        - make install

    - name: "linux cmake clang"
      os: linux
      dist: xenial
      compiler: clang
      sudo: required
      env: QT_SELECT="opt-qt511"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:beineri/opt-qt-5.11.1-xenial"
          update: true
          packages:
            - qtbase5-dev
            - qt511-meta-full
            - libbullet-dev
      script:
        - mkdir build
        - cd ./build
        - cmake -DQt5Widgets_DIR=/opt/qt511/lib/cmake/Qt5Widgets/ ..
        - cmake --build . --target install

    - name: "linux qmake clang"
      os: linux
      dist: xenial
      compiler: clang
      sudo: required
      env: QT_SELECT="opt-qt511"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:beineri/opt-qt-5.11.1-xenial"
          update: true
          packages:
            - qtbase5-dev
            - qt511-meta-full
            - libbullet-dev
      script:
        - mkdir build
        - cd ./build
        - qmake ..
        - make
        - make install